This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./Draft-46-PhD-Proposal-WRY.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Draft-46-PhD-Proposal-WRY.acn....done (102 entries accepted, 0 rejected).
Sorting entries....done (693 comparisons).
Generating output file Draft-46-PhD-Proposal-WRY.acr....done (119 lines written, 0 warnings).
Output written in Draft-46-PhD-Proposal-WRY.acr.
Transcript written in Draft-46-PhD-Proposal-WRY.alg.
